### Numpy Intro

**NumPy** is a library written for scientific computing and data analysis. It stands for numerical python.

The most basic object in NumPy is the ```array```, which is **homogenous** in nature. By homogenous, we mean that all the elements in a numpy array have to be of the **same data type**, which is commonly numeric (float or integer). 

**NumPy** is kind of a MATLAB replacement,  useful in **plotting** (Matplotlib), **Backend** (Pandas, Digital Photography), **Machine Learning**. **Tensors** are pretty connected to numpy library

In [58]:
import numpy as np
a = np.array([1,3,5])      # we can multiply two numpy arrays but can not do the same in lists
b = np.array([2,4,6])
print(a*b)

[ 2 12 30]


### Load in Numpy (remember to pip install numpy first)

In [59]:
import numpy as np

In [60]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [61]:
b = np.array([[1,2,3,4], [4,2,33,3]])
print(b)

[[ 1  2  3  4]
 [ 4  2 33  3]]


In [62]:
# get dimension
print(a.ndim)
print(b.ndim)

1
2


In [63]:
# get shape
print(a.shape)  # will give us rows and columns (2D)
print(b.shape)

(6,)
(2, 4)


In [64]:
# get type
print(a.dtype)    # 32 tell us about bits i.e. (1 byte = 8 bits)
print(b.dtype)

int32
int32


In [65]:
# get size
print(a.itemsize)   # it will give us the answer in bytes
print(b.itemsize)
print(a.size)      # it will gives us the total no of elements in a
print(b.size)

4
4
6
8


In [66]:
# to get the total size of a
print(a.size * a.itemsize)   # or
print(a.nbytes)

24
24


### Accessing & Changing specific elements, rows, col, etc

In [67]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [68]:
# get a specific element [row,col]
print(a[1,4])           # indexing starts from 0 so for 2nd row and 5th coloumn we write a[1,4]
print(a[1,-2])

11
11


In [69]:
# get a specific row
print(a[0,:])        # to get the whole 1st row
print(a[:,2])        # to get the whole 3rd coloumn

[1 2 3 4 5 6]
[3 9]


In [70]:
# getting a little more fancy [startindex:endindex:stepsize]
print(a[1,1:6:2])      # taking out the 1st row and from coloumn 2 to 7 with alternate nos

[ 8 10 12]


In [71]:
a[1,5] = 20     # redefining element possible as it is mutable (row 2nd coloumn 6th)
print(a)
a[:,3] = 5
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 20]]
[[ 1  2  3  5  5  6]
 [ 7  8  9  5 11 20]]


In [72]:
# 3d example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [73]:
print(b[0,1,1])      # going in 1st set and then from [[1,2],[3,4]] we want 2nd row and from [3,4] we want 2nd element

4


### Initializing differents types of arrays

In [74]:
# all 0's matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [75]:
# all 1's matrix
np.ones((4,2,2), dtype='int32')         # dtype converts float to int or vice versa

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [76]:
# any other number
np.full((2,2),99)            # 2 rows and 3 coloumns with custom no

array([[99, 99],
       [99, 99]])

In [77]:
# full_like method which helps us to take shape that has already been built
print(np.full_like(a,4))
print(np.full(a.shape,6))

[[4 4 4 4 4 4]
 [4 4 4 4 4 4]]
[[6 6 6 6 6 6]
 [6 6 6 6 6 6]]


In [78]:
# random decimal numbers
print(np.random.rand(4,2))    # or
print(np.random.random_sample(a.shape))

[[0.4023462  0.06984653]
 [0.55886224 0.37103125]
 [0.98257172 0.45356761]
 [0.80667055 0.17039755]]
[[0.30893545 0.25220788 0.28159313 0.07869157 0.3460003  0.34257757]
 [0.33186538 0.42137399 0.43924209 0.64600941 0.73090074 0.87261007]]


In [79]:
# random iinteger values
np.random.randint(-7,9, size=(3,3))            # between -7 and 9 we can have values in the matrix

array([[ 7, -5, -2],
       [ 5,  3,  6],
       [ 8, -3,  7]])

In [80]:
# identity matrix     ( so it will have to be square matrix - equal row and coloumn)
np.identity(5, dtype='int32')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [81]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)        # to repeat it 3 times
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [82]:
first_step = np.ones((5,5), dtype='int32')
print(first_step)

second_step = np.zeros((3,3),dtype='int32')
second_step[1,1] = 9      # 2nd row & 2nd col
print(second_step)

first_step[1:4,1:4] = second_step    # replacing from 2nd to 5th row & 2nd to 5th col 
print(first_step)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### While copying any array be careful

In [83]:
# use copy method and dont use directly b = a
a = np.array([1,2,3])        
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


## Mathematics

In [84]:
a = np.array([1,2,3,4])
print(a+2, a*2, a/2, a**2)

[3 4 5 6] [2 4 6 8] [0.5 1.  1.5 2. ] [ 1  4  9 16]


In [85]:
b = np.array([0,1,0,1])
print(a+b)

[1 3 3 5]


In [86]:
# take the sin
print(np.cos(a))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


### Linear Algebra

In [87]:
a = np.ones((2,3))
b = np.full((3,2), 2)

print(np.matmul(a,b))          # multiplying two matrix

[[6. 6.]
 [6. 6.]]


In [88]:
c = np.identity(3)
print(c)
print('--------------')
print(np.linalg.det(c))          # det of identity matrix is 1,   linalg means linear algebra

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
--------------
1.0


In [89]:
print(np.trace(c))          # returns the sum of diagonal elements
print(np.linalg.det(c))     # returns the det of 
print(np.linalg.norm(c)) 
print(np.linalg.eigvals(c))        # returns the eigen value of matrix
print(np.linalg.inv(c))     # returns the inverse of a matrix

3.0
1.0
1.7320508075688772
[1. 1. 1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Statistics

In [90]:
stats = np.array([[1,2,3],[4,5,6]])
print(np.min(stats))
print(np.min(stats, axis=1))             # axis means both arrays considered min of 1st array 1 and min of 2nd array 4

1
[1 4]


In [91]:
print(np.sum(stats))
print(np.sum(stats, axis=0))
print(np.sum(stats, axis=1))

21
[5 7 9]
[ 6 15]


### Reorganizing Arrays

In [92]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)
print('----------------')
print(before.shape)
print('----------------')
after = before.reshape((8,1))    # row * col = no of elements in array (ofc)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
----------------
(2, 4)
----------------
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [93]:
# vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(np.vstack([v1,v2,v2,v2]))   # it simply helps combining/stacking two different arrays into one

[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]]


In [94]:
h1 = np.ones((2,4))
print(h1)
print('-----------------------')
h2 = np.zeros((2,2))
print(h2)
print('-----------------------')

print(np.hstack((h1,h2)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
-----------------------
[[0. 0.]
 [0. 0.]]
-----------------------
[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


## Miscellaneous

### Load Data from File

In [95]:
from io import StringIO   # StringIO behaves like a file object
c = StringIO("0 1 \n 2 3")
filename = np.genfromtxt(c)   # or np.loadtxt(c); main thing here to notice; it would load the data from file to here
print(filename)
print(filename.astype('int32'))    # it converts in whatever we want it to be but not permanent

[[0. 1.]
 [2. 3.]]
[[0 1]
 [2 3]]


In [96]:
# if u want the above permanently then equate it with a variable name
filedata = filename.astype('int32')
print(filedata)

[[0 1]
 [2 3]]


### Boolean Masking and Advanced Indexing

In [97]:
print(filedata >= 2)
print('-----------------')
print(filedata[filedata >=2])     # will only grab the numbers which are true for the condition

[[False False]
 [ True  True]]
-----------------
[2 3]


In [98]:
print(np.any(filedata>=2, axis=1))      # axis = 0 means coloumn & axis = 1 means rows
print('--------------')
print(np.all(filedata>=2, axis=1))

[False  True]
--------------
[False  True]


In [99]:
# you can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8])
print(a[[1,2,3]])          # at position 2nd,3rd,4th we have 2,3,4 as indexing starts from 0

[2 3 4]


In [100]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])